#' Example tidy expression dataset for heatmap plotting
#'
#' A small long-format data frame with simulated gene expression values across
#' three samples, intended for use in \code{\link{plot_heatmap}} examples and
#' tests.
#'
#' @format A data frame with 9 rows and 10 columns:
#' \describe{
#'   \item{external_gene_name}{Character. Gene identifier (GeneA–GeneC).}
#'   \item{sample}{Character. Sample identifier (S1–S3).}
#'   \item{expression}{Numeric. Simulated expression value.}
#'   \item{is_immune_gene}{Character. Whether the gene is an immune gene
#'     (\code{"yes"} or \code{"no"}).}
#'   \item{direction}{Character. Expression direction (\code{"up"} or
#'     \code{"down"}).}
#'   \item{log2fc}{Numeric. Log2 fold change.}
#'   \item{sample_type}{Character. Sample type (\code{"input"} or \code{"IP"}).}
#'   \item{condition}{Character. Experimental condition (\code{"healthy"} or
#'     \code{"EAE"}).}
#'   \item{group}{Character. Sample grouping (\code{"G1"} or \code{"G2"}).}
#'   \item{qc_score}{Numeric. Quality control score (0–1).}
#' }
#'
#' @source Generated by \code{inst/prepare_data/data_exprs_small.R}.
"ex_data_heatmap"

#' Hallmark gene sets (Human) from MSigDB
#'
#' A two-column data frame mapping MSigDB Hallmark gene-set names to human gene
#' symbols, as retrieved from MSigDB v2024.1 via the \pkg{msigdbr} package.  The
#' \code{"HALLMARK_"} prefix has been stripped from term names for brevity.
#'
#' This object is provided as bundled package data so that
#' \code{\link{run_gsea}}, \code{\link{plot_pathways}}, and
#' \code{\link{plot_pathway_correlation_network}} examples can run without an
#' internet connection or an \pkg{msigdbr} installation.
#'
#' @format A data frame with 7,322 rows and 2 columns:
#' \describe{
#'   \item{term}{Character. Hallmark gene-set name (\code{"HALLMARK_"} prefix
#'     removed).}
#'   \item{gene}{Character. HGNC gene symbol.}
#' }
#'
#' @source Retrieved with \code{msigdbr(species = "Homo sapiens", collection =
#'   "H")} and regenerated by \code{inst/prepare_data/hallmark_t2g.R}.
"hallmark_t2g"

#' Example expression matrix for pathway correlation network plots
#'
#' A 20-gene × 40-sample simulated expression matrix used in
#' \code{\link{plot_pathway_correlation_network}} examples.  Genes are drawn
#' from the \code{MYC_TARGETS_V1} Hallmark pathway.  Three small correlated
#' gene modules are embedded (within-module Pearson r ≈ 0.9) alongside six
#' independent genes, giving a realistic sparse network.
#'
#' @format A numeric matrix with 20 rows (genes) and 40 columns (samples).
#'   Row names are HGNC gene symbols; column names are \code{S1}–\code{S40}.
#'
#' @seealso \code{\link{ex_log2fc_pathway}}, \code{\link{plot_pathway_correlation_network}}
#' @source Generated by \code{inst/prepare_data/ex_pathway_data.R}.
"ex_expr_pathway"

#' Hallmark pathway process categories
#'
#' A two-column data frame mapping each MSigDB Hallmark gene-set name to its
#' biological process category, as defined in Table 1 of Liberzon et al.
#' (2015).  Categories are: \code{"cellular_component"}, \code{"development"},
#' \code{"DNA_damage"}, \code{"immune"}, \code{"metabolic"}, \code{"pathway"},
#' \code{"proliferation"}, and \code{"signaling"}.
#'
#' @format A data frame with 50 rows and 2 columns:
#' \describe{
#'   \item{term}{Character. Hallmark gene-set name, with the \code{"HALLMARK_"}
#'     prefix removed to match the \code{term} column of \code{\link{hallmark_t2g}}.}
#'   \item{process_category}{Character. Biological process category assigned in
#'     Liberzon et al. (2015), Table 1.}
#' }
#'
#' @references Liberzon, A., Birger, C., Thorvaldsdóttir, H., Ghandi, M.,
#'   Mesirov, J. P., & Tamayo, P. (2015). The Molecular Signatures Database
#'   hallmark gene set collection. \emph{Cell Systems}, \strong{1}(6), 417–425.
#'   \doi{10.1016/j.cels.2015.12.004}
#'
#' @source Process categories taken from Table 1 of Liberzon et al. (2015).
#'   Data prepared by \code{inst/prepare_data/hallmark_pathway_categories.R}.
"hallmark_pathway_categories"

#' Example GSEA result for plot_pathways and plot_pathway_correlation_network
#'
#' A pre-computed GSEA result generated by [run_gsea()] using a random
#' gene-score vector and the bundled [hallmark_t2g] gene sets.  Provided so
#' that [plot_pathways()] and [plot_pathway_correlation_network()] examples can
#' run without requiring \pkg{clusterProfiler} to be installed.
#'
#' @format A list with three elements as returned by [run_gsea()]:
#' \describe{
#'   \item{`gsea_result`}{A `gseaResult` object from [clusterProfiler::GSEA()].}
#'   \item{`gene_vec`}{Named numeric vector of gene scores (sorted decreasing).}
#'   \item{`term2gene`}{Two-column data frame with columns `term` and `gene`.}
#' }
#'
#' @source Generated by \code{inst/prepare_data/ex_gsea_result.R}.
#' @seealso [run_gsea()], [plot_pathways()], [plot_pathway_correlation_network()]
"ex_gsea_result"

#' Example log2 fold-change vector for pathway correlation network plots
#'
#' A named numeric vector of simulated log2 fold changes for the 20 genes in
#' \code{\link{ex_expr_pathway}}, used to color nodes in
#' \code{\link{plot_pathway_correlation_network}} examples.
#'
#' @format A named numeric vector of length 20.  Names are HGNC gene symbols
#'   matching the row names of \code{\link{ex_expr_pathway}}.
#'
#' @seealso \code{\link{ex_expr_pathway}}, \code{\link{plot_pathway_correlation_network}}
#' @source Generated by \code{inst/prepare_data/ex_pathway_data.R}.
"ex_log2fc_pathway"
